### ISSUE TITLE
3-fold repetition problem in janggi

### ISSUE THREAD

**Issue by naramy** [ianfab/Fairy-Stockfish#186] opened 2020-09-23 08:03 UTC
Hi. I found problem for 3-fold repeat.

![image](https://user-images.githubusercontent.com/48436057/93977185-13201900-fdb5-11ea-8b0a-ebb6e30e2871.png)

Fen : 3a1a2r/4k4/2n1cn1c1/1pp1bb2p/2r2pp2/1PCP5/3PB1PP1/2N1CN3/4A4/R3KA1BR b 0 1

This is Black(Han) turn. Fairy-SF's variant is janggicasual. so, nFoldValue is VALUE_DRAW.
in janggicasual, Fairy-SF finds e6g3.
but in janggimodern, Fairy-SF can't find e6g3. because Fairy-SF thinks e6g3 is bad for Black(Han).

Fairy-SF says Black(Han) trys to repeat, but XBoard says White(Cho) trys to repeat.

also, this position is good for Black(Han).
e6g3 -> h3g3 -> f6c4 ->
b4c4(first move to White, Cho) -> c5b5(first move to Black, Han) ->
c4b4(second move to White, Cho) -> b5c5(second move to Black, Han) ->
b4c4(third move to White, Cho) -> c5b5(third move to Black, Han) ->
c4b4(fourth move to White, Cho) -> b5c5(fouth move to Black, Han) ->
b4c4(fifth move to White, Cho)

Because White(Cho) trys to repeat. I think it's Fairy-SF's problem.

![image](https://user-images.githubusercontent.com/48436057/93979641-942cdf80-fdb8-11ea-9260-3990ea651c69.png)

in janggimodern, Fairy-SF says it's White wins. if White(Cho) trys b4c4, XBoard says White wins.

![image](https://user-images.githubusercontent.com/48436057/93980335-73b15500-fdb9-11ea-82fd-7a48feb783be.png)

So, I tried to modify nFoldValue. This is applied "nFoldValue =VALUE_KNOWN_WIN"
In previous image, XBoard says White wins. Is that really right?
maybe XBoard says Black wins.

![image](https://user-images.githubusercontent.com/48436057/93980752-03570380-fdba-11ea-92e3-11c42430c673.png)

Fairy-SF says White wins, but XBoard says Black wins.
Is that unknown action? I think "Black wins" message is correct.

And, Sometimes, Fairy-SF in janggimodern finds checkmate using repeatition, but King and Wazir can't applied repeatition.
Because of nFoldValue is -VALUE_MATE, Fairy-SF finds checkmate using repeatition.

![image](https://user-images.githubusercontent.com/48436057/93982501-45814480-fdbc-11ea-806b-8ecb9ad8c54c.png)

Fen : 3k5/9/2Ba5/9/9/3n2B2/9/4CA3/3CA4/5K3 w 0 1

Checkmate is found by Fairy-SF in janggimodern, but it isn't true.

![image](https://user-images.githubusercontent.com/48436057/93983144-259e5080-fdbd-11ea-910d-35274d84e0fb.png)

Maybe, if nFoldValue is VALUE_KNOWN_WIN or VALUE_DRAW(VALUE_NONE), Fairy-SF can find checkmate not using repeatition.

Thanks for reading this issue. I use well Fairy-SF for janggi.
Thank you for making Fairy-SF.

**Comment by ianfab** [comment] 2020-09-23 09:35
Thanks for your feedback. The repetition handling for the "janggimodern" variant is quite different from the other three Janggi rule sets available in Fairy-Stockfish, since the "janggimodern" variant is supposed to be as compatible as possible with the rules in Kakao Janggi (even if I personally do not like these rules). This topic seems to be a bit controversial and has been discussed several times (e.g., https://github.com/ianfab/Fairy-Stockfish/issues/142), but there has not been any clear conclusion yet.

**Comment by naramy** [comment] 2020-09-23 12:21
The repetition handling for the "janggi" and "janggimodern" variants will be more difficult than it for the "janggitraditional" and "janggicasual" variants.
The "janggitraditional" and "janggicasual" variants don't care of repeatition. Because it doesn't matter whether Fairy-SF win or draw. That is traditional and casual.

But, the "janggi" and "janggimodern" variants should care of repeatition. Because, that variant's goal is win, not a draw.
Generally, if the repetition handling's result is a draw, a draw rate of the games is maybe high. Because Attacker of Fairy-SF don't care of repetition. If the odds are stacked against defender, defender of it may try to repeat to draw the game.
Fairy-SF of "janggimodern" variant will use repetition for an advantage, and Fairy-SF of "janggi" variant will use repetition for a draw. Is that right?
But, even if Fairy-SF of that variants has an advantage in the game, it doesn't prepare for repetition. So, Fairy-SF can have not only an advantage for a repetition, but also disadvantage for it. Fairy-SF should be able to catch the loop of repeatition for preapre evaluatation.

And then, the traditional janggi repetition rule is a draw. But in modern, realistically the person who first attempted to repeat should give up.
It was judged based on this fact, and the developer's opinion may be different.

It's okay if you don't care of this problem. It's only my opinion.
Have a good day! Thanks again.

**Comment by ianfab** [comment] 2020-09-23 12:58
The problem is mostly around "who first attempted to repeat should give up", because it is far from trivial to define which player is to blame for the repetition. First of all there are different ways how to identify a repetition (e.g., repetition of a position, repetition of moves by both sides, repetition of moves by one side), and there can be different rules how to determine which side "forces" the repetition (raw count of repetitions, determining the more/less valuable piece, considering attackers/defenders of pieces, etc.). 

Since there is no precise definition of repetition rules in Janggi (in contrast to the extensive chasing rules in Xiangqi), and in practical tournament play mostly is up to the arbiter to decide, it is hard to find a consistent solution. I am open to suggestions for improvements, but this topic is quite time consuming since it has already been discussed countless times, so I ask everyone who is dissatisfied with the current solution to first try to understand the actual problem of defining repetition rules (e.g., at the example of chasing rules in Xiangqi), because otherwise any discussion will be fruitless.

**Comment by naramy** [comment] 2020-09-23 22:26
The repetition handling for the "janggimodern" variant is based on Kakao Janggi rules.
In my opinion, Kakao Janggi is focused on "Piece" and "Position".
For example, https://www.pychess.org/jxofROzz the cannon can choose between going back to 29 and 39 (when being on the 59 square), and then Kakao Janggi says Cho trys to repeat.
This is only focused on Solider moving left and right. Cannon moves up and down but not in same position.

But, the repetition handling for "janggi" variant is difficult. The "chase" didn't be established,
The Perpetual Check is disqualified. It loses the game.

The repetition in xiangqi uses a cannon, a rook, or a horse.
Xiangqi's cannon moves up, down, left and right without other pieces. Janggi's cannon can't move without other pieces. This difference makes that Janggi's cannon doesn't have "one check and one threatening to checkmate" situation. Since the cannon of janggi is passive, it can be seen there are few repetitions related to check.

Rather, the repetition can occur in situations similar to the following:

![image](https://user-images.githubusercontent.com/48436057/94059724-d0465b80-fe1d-11ea-97a5-ae0d8e1157e9.png)

If it evaluates correctly, this situation can catch the rook even if the morphological repetition continues. Han have to move b6 solider for defence the rook, Cho moves a3 solider, c0 elephant, c2 horse for catching the rook.
Is it a repetition? No. Han had to move b6 solider, it's forced move. Cho moves iteratively, but it doesn't have a loop.

![image](https://user-images.githubusercontent.com/48436057/94063266-d12dbc00-fe22-11ea-89aa-bc7fa6036781.png)

That is the result. Cho can catch the rook.

But, the repetition of a rook in Janggi is a problem as same as in Xiangqi. So, I decided to see and judge xiangqi repetition rule.
I refer to "http://www.clubxiangqi.com/rules/asiarule.htm"
Because, I think examples of Xiangqi is similar to Janggi.
In Section 4, Number 6, 7, 8, 9, 11, 12, 13, 16, 19, 21, 23, 27, 28, 32, 33, 40 isn't allowed.
Number 10 can't watch the image, Number 14 may be repetition, but i don't know why so.
Number 15, 17. 18, Diagram 96 in Number 37, Diagram 97 in Number 38, Number 39 uses cannon in Xiangqi actively, so can't applied to Janggi.
Number 16, Diagram 51, 52, 55 in Number 24, Number 25, Diagram 69 in Number 29, Diagram 71, 73 in Number 30, Number 34, Number 35, Number 36, Diagram 94, 95 in Number 37 can be similarly applied to Janggi.
Number 22 can move that. and then it will evaluate Piece Score.
Diagram 72 in Number 30 can be similarly applied to Janggi. but the cannon is replaced to a rook, and then Red's two Pawns have to be protected.
I think Black Pawn of Diagram 74 in Number 31 doesn't have to move for avoiding Red Rook. but Diagram 75 in Number 31 isn't allowed.
Diagram 98 in Number 38 can be similarly applied to Janggi. but Black cannon is replaced to a rook.

I don't think there are many repetitions of a horse and an elephant. But, it's only my thinking. In reality, it may be many repetitions of them.

Looking at xiangqi's repetition rules, I felt that there were many situations that had to be elaborately judged. In some cases, the interpretation of the situation has varied. It seems that it is difficult to set the repetition rules.

Thanks for giving me a hint so I could learn.

**Comment by ianfab** [comment] 2020-09-28 14:08
Thanks for your feedback. This is still an open issue, but in order to have a single place for discussion of this topic, I am closing this in favor of #142.

**Closed by ianfab** 2020-09-28 14:08 UTC
Labels: duplicate
