### ISSUE TITLE
Handling of missing castling rights in FEN

### ISSUE THREAD

**Issue by CouchTomato87** [ianfab/Fairy-Stockfish#70] opened 2020-01-27 11:19 UTC
Using this as the variants.ini config:

# Shogun
[1shogun:crazyhouse]
variantTemplate = shogi
pieceToCharTable = PNBR.D.....++++.+Kpnbr.d.....++++.+k
pocketSize = 8
startFen = rnb+dkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNB+DKBNR w KQkq - 0 1
commoner = c
centaur = g
archbishop = a
chancellor = m
fers = d
promotionRank = 6
promotionLimit = g:1 a:1 m:1 q:1
promotionPieceTypes = -
promotedPieceType = p:c n:g b:a r:m d:q
mandatoryPawnPromotion = false
firstRankPawnDrops = true
promotionZonePawnDrops = true
whiteDropRegion = *1 *2 *3 *4 *5
blackDropRegion = *4 *5 *6 *7 *8
immobilityIllegal = true

I was running some games with Fairy vs itself... Invariably, black would stop working after white performed O-O. After forcing the game through, there was another situation where black wouldn't think after Re1. In either cases, if I paused the game and "started over" to make black think again from that position, it would perform an illegal move, such as trying to drop a knight it didn't have.

**Comment by ianfab** [comment] 2020-01-27 13:31
From the description it is pretty clear that the castling move is ignored by Fairy-Stockfish and after that the GUI and engine are out of sync (since the xboard protocol is stateful), so any further moves can not be applied properly.

I will try to reproduce it and see if Winboard/XBoard uses a non-standard format for the castling move or whether the engine does not properly parse the move. I suspect it might have to do with https://github.com/ianfab/Fairy-Stockfish/commit/ea594ce74a3013d0d186a272e2890493bfefea24.

**Comment by ianfab** [comment] 2020-01-27 19:44
The issue actually does not seem to be with the castling move format, but rather with the starting FEN. The problem is that Winboard removes castling rights from the FEN for variants derived from shogi, but it only sends this wrong starting FEN to the second engine, so basically one engine plays with and the other without castling rights.

I can try to add a workaround, but the core problem is that Winboard does not handle hybrid variants of chess and shogi very well.

**Comment by ianfab** [comment] 2020-01-27 20:02
A possible workaround is to set `setboard=0` in https://github.com/ianfab/Fairy-Stockfish/blob/d1a1c7b157e59e4344ad2ab478b16c790d708cb3/src/xboard.cpp#L111 Then it is no longer possible to play from a custom starting position, but at least playing from the starting position works correctly. This can not be properly fixed without changes in Winboard.

**Closed by ianfab** 2020-01-27 20:02 UTC
Labels: wontfix
