### ISSUE TITLE
FairySF overlooking/underestimating risk of checkmate in a Sittuyin endgame

### ISSUE THREAD

**Issue by notruck** [ianfab/Fairy-Stockfish#156] opened 2020-06-24 14:30 UTC
In this position, Black can likely get a draw with a sensible defense. 

![FairySF-walking-into-the-corner](https://user-images.githubusercontent.com/56622488/85569665-97f96c00-b5e7-11ea-95ca-821f6cec2d88.png)

`FEN: 8/5k2/8/4KN2/4F3/p7/8/f7 b - - 8 53`

In the game, FairySF had Black, and voluntarily retreated the King into the dangerous corner. The game continued: 53...Kg8 54. Ke6 Kh8 after which 55. Kf7 traps it in the corner, with imminent mate. (The Ferz comes around to g6, Kf8 and Nf7#)
```

53...Kg8 {-0.13/47 8.5s} 54. Ke6 Kh8 {-0.13/46 8.9s} 55. Kf7 {+M15} Kh7 {-0.13/48 8.7s}
56. Ff3 {+M13} Fb2 {-M12/137 25s}  
```

Seeing that it reached depths of 40+ and still overlooked the mate, I got curious and ran a quick analysis on the position after Black's 54...Kh8, with the latest master, and also the provided FairySF 11.1 binary. The latest Master did not detect the deadly 55. Kf7 until depth 41. 

```
34 13 474 6408674 39 1349478 0	 e6e5 h8h7 e5f6 a3a2 f5d6 h7g8 e4f5 a1b2 d6f7 b2c1 f5g4 g8h7 f7g5 h7h6 g4f5 h6h5 f5g6 h5h4 g5f3 h4h3 f6e5 h3g3 e5e4 g3f2 f3e5 c1d2 g6h7 d2c1 e4d3 f2f1 d3c4 c1d2 e5d3 d2e1 h7g8 e1f2
35 13 750 10333127 45 1377015 0	 e6e5 h8h7 e5f6 a3a2 f5d6 a1b2 e4f5 h7g8 d6f7 b2c1 f5g4 g8h7 f7g5 h7h6 g4f5 h6h5 f5g6 h5h4 g5f3 h4h3 f6e5 h3g3 e5e4 g3f2 f3e5 c1d2 e5g4 f2g3 g4f6 g3g2 e4d3 d2e1 f6h7 g2h1 d3c3 e1f2 c3d3 f2g3 h7g5 g3h2
36 13 918 12747449 41 1388006 0	 e6e5 h8h7 e5f6 a3a2 f5d6 a1b2 e4f5 h7g8 d6f7 b2c1 f5g4 g8h7 f7g5 h7h6 g4f5 h6h5 f5g6 h5h4 g5f3 h4h3 f6e5 h3g3 e5e4 g3f2 f3e5 c1d2 e5g4 f2g3 g4f6 g3g2 e4d3 d2e1 g6h5 g2h1 d3c3 h1g1 f6e8 e1f2 c3b3 f2g3
37 13 1415 19530884 47 1380274 0	 e6e5 h8h7 e5f6 a1b2 e4f3 h7g8 f5h6 g8f8 h6f7 a3a2 f7e5 b2c1 e5g6 f8e8 f6e5 c1d2 e5d4 d2e1 d4d3 e1f2 d3c4 f2e1 c4b3 e1f2 b3a2 f2g1 a2b2 g1h2 f3g2 h2g1 g6f4 g1h2 g2f1 h2g3 f4e6 g3f2 b2a2 f2g1 e6c7 e8d7
38 13 1550 21425982 40 1381964 0	 e6e5 h8h7 e5f6 a1b2 e4f3 h7g8 f5h6 g8f8 h6f7 a3a2 f7e5 b2c1 e5g6 f8e8 f6e5 c1d2 e5d4 d2e1 d4d3 e1f2 d3c4 f2e1 c4b3 e1f2 b3a2 f2g1 a2b2 g1h2 f3g2 h2g1 g6f4 g1h2 g2f1 h2g3 f4h5 g3f2 h5f6 e8e7 f6e4 f2e1
39 13 1785 24696688 42 1383025 0	 e6e5 h8h7 e5f6 a1b2 e4f3 h7g8 f5h6 g8f8 h6f7 a3a2 f7e5 b2c1 e5g6 f8e8 f6e5 c1d2 e5d4 d2e1 d4d3 e1f2 d3c4 f2e1 c4b3 e1f2 b3a2 f2g1 a2b2 g1h2 f3g2 h2g1 g6f4 g1h2 f4e6 h2g3 b2a2 g3f2 g2h1 f2g1 e6g5 g1h2
40 13 2025 28134129 44 1388928 0	 e6e5 h8h7 e5f6 a1b2 e4f3 h7g8 f5h6 g8f8 h6f7 a3a2 f7e5 b2c1 e5g6 f8e8 f6e5 c1d2 e5d4 d2e1 d4d3 e1f2 d3c4 f2e1 c4b3 e1f2 b3a2 f2g1 a2b2 g1h2 f3g2 h2g1 g6e5 e8d8 e5g4 d8c7 g2f1 c7b6 b2b3 b6c5 g4e5 c5b5 b3c3 g1f2
41 23 2267 31682930 46 1397262 0	 e6f7
41 32 2273 31766531 46 1397559 0	 e6f7
41 47 2276 31821712 46 1397896 0	 e6f7
41 67 2282 31922956 46 1398473 0	 e6f7
41 94 2287 32016179 46 1399369 0	 e6f7
41 130 2322 32684319 50 1407108 0	 e6f7
41 178 2322 32686267 50 1407131 0	 e6f7
41 100008 2322 32686370 50 1407136 0	 e6f7
41 100008 2322 32686805 50 1407155 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
42 100008 2326 32761306 16 1408422 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
43 100008 2329 32838892 16 1409939 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
44 100008 2330 32874132 16 1410362 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
45 100008 2332 32893149 16 1410512 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
46 100008 2332 32900688 16 1410593 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
47 100008 2334 32933568 16 1411035 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
48 100008 2334 32945190 16 1411110 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
49 100008 2335 32966660 16 1411304 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
50 100008 2337 32987574 16 1411535 0	 e6f7 a3a2 f5h6 a1b2 e4f5 h8h7 h6g4 h7h8 f5g6 b2c1 f7f8 a2a1 g4e5 c1b2 e5f7
```
The latest binary release of FairySF 11.1 downloaded from this repo, detected the move Kf7 a little earlier at depth 37, but didn't seem to realize it's fatal until depth 44:

```
30 13 103 1332321 36 1293515 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a3f f2e2 e7d6 e2d2 d6e6 e4f3 e6e7 a6c5 e7f6 c5d3
31 13 140 1797682 38 1279488 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a3f f2e3 e7d7 e3d2 d7d6 d2c3 d6e5 e4f3 e5f5 c3b3 f5f4 f3g2
32 13 168 2145161 36 1274605 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a2 a6c5 a2a2f c5d3 e7d6 f2e3 a2b3 e3d4 d6c6 d4c3 b3a4 c3c2 a4b5
33 13 205 2597929 42 1263584 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a2 a6c5 a2a2f c5d3 e7d6 f2e3 a2b3 e3d4 d6c6 d3e5 c6b5 d4c3 b3a4 c3d4 b5b4 d4d3 b4a3
34 13 276 3526438 43 1274002 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a2 a6c5 a2b1f f2e3 b1c2 e4f3 e7d6 c5b7 d6e5 e3d2 e5f4 d2c2 f4f3 c2c1 f3f4 b7c5 f4e5
35 13 349 4425329 43 1266550 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e1f2 e2f2 a3a2 a6c5 a2b1f f2e3 b1c2 e4f3 e7d6 c5a6 d6e5 a6b4 c2d1 e3d2 e5f4 f3g2 f4g3 d2d1 g3g2
36 13 495 6160288 42 1243497 0	 f5e3 h8g8 e4d5 a1b2 e3c2 g8f8 d5e4 f8e8 e6d5 e8d7 c2b4 d7e7 b4a6 b2c1 d5c4 c1d2 c4d3 d2e1 d3e2 e7d6 e4f3 e1f2 e2f2 a3b2f f2e3 d6d5 e3d3 d5e5 a6c5 e5f4 f3g2 b2c1 d3c2 f4e3 c2c1 e3f2 c1b2 f2g2
37 23 605 7611499 44 1256645 0	 e6f7
37 32 616 7756008 44 1257459 0	 e6f7
37 47 624 7851173 44 1257797 0	 e6f7
37 67 628 7901667 44 1257826 0	 e6f7
37 94 633 7968388 44 1257835 0	 e6f7
37 130 635 8001077 44 1258624 0	 e6f7
37 178 638 8040611 44 1259691 0	 e6f7
37 204 652 8238993 44 1262680 0	 e6f7 h8h7 f5g3 h7h6 f7f6 a1b2 e4f5 h6h7 f5g6 h7g8 g6f7 g8h7 g3e4 b2c3 e4c3 h7h6 f7g6 a3a2 c3d5 a2a1 g6f5 h6h7 f6e5 a1a1f e5e4 h7h6 e4d3 h6g5 f5e4 g5g6 d3c3 g6h7 c3b3 h7g8 b3a2 g8h8 a2a1
38 215 656 8306614 37 1264902 0	 e6f7
38 225 662 8408004 48 1268558 0	 e6f7
38 240 670 8517260 50 1270663 0	 e6f7
38 261 691 8838777 55 1277833 0	 e6f7
38 242 737 9508508 55 1288939 0	 e6f7 h8h7 f5g3 h7h6 f7f6 a1b2 e4f5 h6h7 f5g6 h7g8 g6f7 g8h7 g3e4 b2c3 e4c3 h7h8 f6g6 a3a2 c3d5 a2a1 g6f6 h8h7 f7g6 h7h6 g6f5 h6h5 f6e5 a1a1f e5d4 h5g5 f5e4 g5h4 d4d3 h4g5 d3c2 g5g6 c2b1 g6f7 e4f5 f7g7 b1a1 g7h7 a1b2 h7h6 f5e4 h6g5 b2c3 g5h6 c3c2 h6g7 c2b2 g7f8 b2c3
39 253 772 9989306 53 1293448 0	 e6f7
39 263 782 10159473 53 1298003 0	 e6f7
39 279 823 10843535 57 1317081 0	 e6f7
39 257 845 11166129 58 1320497 0	 e6f7 h8h7 f5g3 h7h6 f7f6 a1b2 e4f5 h6h7 f5g6 h7g8 g6f7 g8h7 g3e4 h7h8 f6g6 b2c3 e4c3 a3a2 c3d5 a2a1 g6f6 h8h7 d5b4 h7h6 b4c2 h6h5 c2a1 h5g4 f6e5 g4f3 a1c2 f3e2 e5d4 e2f3 c2e3 f3f4 f7e6 f4g5 d4e5 g5g6 e3d5 g6h6 e5f6 h6h5 e6f5 h5h4 d5b4 h4g3 f6e5 g3f3 b4d5 f3g3
40 246 881 11679369 58 1324491 0	 e6f7 h8h7
40 257 903 12046431 59 1333750 0	 e6f7
40 257 910 12136894 61 1332992 0	 e6f7 h8h7 f5g3 h7h6 f7f6 h6h7 e4f5 h7g8 f5g6 a1b2 g6f7 g8h7 g3e4 b2c3 e4c3 h7h6 f7g6 a3a2 c3d5 a2a1 g6f5 h6h5 f6e5 a1a1f e5d4 h5h4 d4c3 h4g3 c3b3 g3f2 f5e4 f2e1 b3a2 e1d1 a2a1 d1c1 a1a2 c1c2 a2a3 c2c1 a3b3 c1d2 b3b2 d2d1 b2c3 d1e2 c3c2 e2e1 d5c3 e1f2 c2d3 f2g3 d3e3 g3g4 e3d4 g4g5 d4e5 g5g6 e4f5 g6f7 c3d5
41 257 937 12539188 65 1337370 0	 e6f7 h8h7 f5g3 h7h6 f7f6 h6h7 e4f5 h7g8 f5g6 a1b2 g6f7 g8h7 g3e4 b2c3 e4c3 h7h6 f7g6 a3a2 c3d5 a2a1 g6f5 h6h5 f6e5 a1a1f e5d4 h5h4 d4c3 h4g3 c3b3 g3f2 f5e4 f2e1 b3a2 e1d1 a2a1 d1c1 a1a2 c1c2 a2a3 c2c1 a3b3 c1d2 b3b2 d2d1 b2c3 d1e2 c3c2 e2e1 d5c3 e1f2 c2d3 f2g3 d3e3 g3g4 e3d4 g4g5 d4e5 g5g6 e4f5 g6f7 c3b5 f7g7 e5e6 g7h6 e6f6
42 268 970 13038279 62 1344152 0	 e6f7
42 268 981 13209085 63 1345394 0	 e6f7 h8h7 f5g3 h7h6 f7f6 h6h7 e4f5 h7g8 f5g6 a1b2 g6f7 g8h7 g3e4 b2c3 e4g5 h7h8 f6g6 c3d4 g5f3 d4e3 f3e5 e3f4 e5c6 f4g5 c6e7 g5f6 g6f6 h8h7 f7g6 h7h8 f6f7 a3b4f f7f8 b4c5 e7c6 c5d6 c6d8 d6e7 f8e7 h8g7 g6f5 g7h6 d8e6 h6h5 e7f6 h5h4 e6d4 h4h3 f6e5 h3h4 d4f3 h4g3 f3d2 g3f2 e5e4 f2g2 e4d3 g2g3 f5g6
43 279 993 13391446 69 1348448 0	 e6f7
43 287 1001 13515118 69 1349487 0	 e6f7 h8h7 f5g3 h7h6 f7f6 h6h7 e4f5 h7g8 f5g6 a1b2 g6f7 g8h7 g3e4 b2c3 e4g5 h7h8 f6g6 c3d4 g5f3 d4e3 f3e5 e3f4 e5c6 f4g5 c6e7 g5f6 g6f6 h8h7 e7c6 a3a3f c6e7 a3b4 f7g6 h7h8 f6f7 b4c5 e7f5 c5d6 f7f8 d6e7 f8e7 h8g8 e7f6 g8f8 f5g7 f8g8 g7e6 g8h8 e6f4 h8g8 g6f7 g8h7 f4d3 h7h8 f7e6 h8g8 d3f4 g8h7 f4d5 h7g8 e6f5
44 298 1027 13892014 68 1352152 0	 e6f7
44 308 1029 13916120 68 1352392 0	 e6f7
44 324 1030 13943026 68 1352772 0	 e6f7
44 346 1031 13957943 68 1353038 0	 e6f7
44 375 1032 13968405 68 1353134 0	 e6f7
44 413 1036 14028298 68 1353168 0	 e6f7
44 100012 1049 14204572 68 1353847 0	 e6f7
44 100008 1049 14210574 68 1353903 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
45 100008 1051 14236273 16 1354030 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
46 100008 1052 14254078 16 1354178 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
47 100008 1053 14269917 16 1354267 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
48 100008 1056 14297553 16 1353806 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
49 100008 1060 14360234 16 1354355 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7
50 100008 1064 14415297 16 1354439 0	 e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3b4 h5g6 h7h8 f5h6 b4c5 f7f8 c5d6 h6f7

```
Could it be a regression of some sort, or maybe something else? Thank you!

**Comment by ianfab** [comment] 2020-06-24 15:40
Thanks, I think this is related to the scaling down of evaluation for small material differences. I already tried a patch for makruk that indeed improved this, but I did not include it yet since I there should be a better solution, but I will check whether that patch would also fix this issue.

**Comment by ianfab** [comment] 2020-06-24 20:27
I am now testing a change https://github.com/ianfab/Fairy-Stockfish/commit/ff3bd8d58d95f2c73711abce6ecf65ec07a8254a that in contrast to the other patch is not just a hack, so if it passes testing I will merge it. It also significantly speeds up the mate finding in the given position.

```
setoption name UCI_Variant value sittuyin
position fen 8/5k2/8/4KN2/4F3/p7/8/f7 b - - 8 53 moves f7g8 e5e6 g8h8
go mate 20
```

```
info depth 44 seldepth 79 multipv 1 score mate 8 nodes 11059497 nps 642657 hashfull 999 tbhits 0 time 17209 pv e6f7 h8h7 e4f3 a1b2 f3g4 b2c3 g4h5 c3d4 h5g6 h7h8 f7f8 d4e5 f5h6 a3a2 h6f7
```

**Comment by ianfab** [comment] 2020-06-30 18:14
The root cause of this issue was that a criterion that should normally only catch draws in K+minor vs. K and KR+minor vs. KR endgames also matched some positions with fairy pieces where it should not apply, which lead to scaling of endgame evaluation differences to zero. This should be fixed by https://github.com/ianfab/Fairy-Stockfish/commit/a271a10e4fdded05a852d84e6191351504d77b29, so I am closing this. If you can still observe such careless endgame play, feel free to reopen this or open a new issue.

**Closed by ianfab** 2020-06-30 18:14 UTC
Labels: playing strength
