### ISSUE TITLE
Bug - Flipello game forces a pass when moves are available

### ISSUE THREAD

**Issue by JamesHeppell** [ianfab/Fairy-Stockfish#508] opened 2022-07-20 14:27 UTC
In the following game, the only move from Fairy-Stockfish is a pass (a1a1) when there are in fact moves available. Not sure what is causing this but if it could be looked into that would be great. 
Also it would be nice to have a consistent pass notation (not sure why it changes throughout a game?), therefore this issue might be linked with https://github.com/ianfab/Fairy-Stockfish/issues/487

UCI moves:
List(
    "P@e3",
    "P@f5",
    "P@e6",
    "P@d7",
    "P@c6",
    "P@d3",
    "P@f4",
    "P@d6",
    "P@c5",
    "P@b5",
    "P@b7",
    "P@b6",
    "P@c7",
    "P@a8",
    "P@f6",
    "P@e7",
    "P@a7",
    "P@b8",
    "P@f7",
    "P@c8", // 10 moves each (20 ply)
    "P@c3",
    "P@a6",
    "P@a5",
    "P@a4",
    "c3c3", // first pass for P1 (1-1)
    "P@d8",
    "c3c3", // another pass for P1 (1-2)
    "P@b4",
    "P@a3",
    "P@a2",
    "c3c3", // second set of passing for P1 (2-1)
    "P@b3",
    "c3c3", // second set of passing for P1 (2-2)
    "P@c4",
    "c3c3", // second set of passing for P1 (2-3)
    "P@c2",
    "P@b2",
    "P@f3",
    "P@b1",
    "P@a1", // 20 moves each (40 ply)
    "P@g3",
    "P@c1",
    "d3d3", // third set of passing for P1 (3-1)
    "P@d2",
    "P@d1",
    "P@e1",
    "d3d3", // fourth set of passing for P1 (4-1)
    "P@e2",
    "e3e3", // fourth set of passing for P1 (4-2)
    "P@f2",
    "P@f1",
    "P@g1",
    "f3f3", // fifth set of passing for P1 (5-1)
    "P@h3",
    "P@g2",
    "P@h1",
    "P@h2",
    "P@g4",
    "P@h4",
    "P@h5", // 30 moves each (60 ply)
    "P@g5",
    "P@h6",
    "e5e5", // sixth set of passing for P1 (6-1)
    "P@g6",
    "P@g7",
    "a1a1", // P2 has moves but only has a valid move to pass for some reason!?
    "e5e5"  // P1 then has no moves and has to pass ending the game
  )
  
![image](https://user-images.githubusercontent.com/20576533/180006964-b01e536d-a6a9-48d0-99e9-b88ca9460174.png)

**Comment by ianfab** [comment] 2022-07-22 17:00
Looks like a possible duplicate of #504. Could you please check?

**Comment by JamesHeppell** [comment] 2022-07-25 09:24
Sorry I missed that, you are right. Player two plays 32 moves and then passes as there are no more drops available. Please mark as duplicate or close as you see fit. 
We thought we had changed our rules version (amending the older version of variants.ini file) to include more drops, but clearly not!

**Comment by ianfab** [comment] 2022-07-25 09:30
Thanks for confirming.

**Closed by ianfab** 2022-07-25 09:30 UTC
Labels: duplicate
