### ISSUE TITLE
Dobutsu repetition should be draw

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#552] opened 2022-12-01 23:27 UTC
https://www.pychess.org/hba7FX5P

**Comment by ianfab** [comment] 2022-12-02 00:40
Closing as (partial) duplicate of #191.

**Closed** 2022-12-02 00:40 UTC

**Comment by gbtami** [comment] 2022-12-02 08:32
Ahh, sorry. I forget about that.

**Comment by gbtami** [comment] 2022-12-02 09:04
Is it OK to create a PR with for Dobutsu with this addition lines?
        v->nFoldValue = VALUE_DRAW;
        v->perpetualCheckIllegal = true;

**Comment by ianfab** [comment] 2022-12-02 10:15
Yes, would be nice, thanks. I guess you meant perpetual check illegal false though.  Also in order to keep the frequency of rule changes low it would be good to include the mandatoryPiecePromotion change as well.
