### ISSUE TITLE
janggi move, illega move between version

### ISSUE THREAD

**Issue by d4soft2021** [ianfab/Fairy-Stockfish#258] opened 2021-02-16 06:10 UTC
I got encountered very strange error recently in janggi(Korean).
I create one PGN file with my own program which convert DOSA file to PGN file.
I developed this converting program  by myself, because dosa file (.gib) is very popular in Korea.
I tested it in my PC (windows 10) 64 bit, and it worked very well.
I sent the PGN file to one of my friends, he tested it in his PC, and got ERROR message (illegal move in 14 move)
He tested it in windows10 too.

He is using BMI version stock-fish, I am using regular largeboard x86-64 version.
His setting /variant=janggimodern
My setting /variant=janggicasual

Unfortunately, He is in Korea, I am in New York USA. We cannot meet in person. He was in New York before, but not now.

the illegal move #14 look like this ===> 14. Ra4 Pc5 ( I open the PGN file in notepad)

Also How can I get this kind of protocol and moving notation in Janggi pieces.
I read document in xboard/winboard blog, but not described full.
Please let me know document describing the protocol between Winboard and Stock-fish Janggi, and moving notation.

Thank you again for your huge effort about janggi program.
I found donation site to you ,https://paypal.me/FairyStockfish
Is it correct ?

**Comment by ianfab** [comment] 2021-02-16 08:56
If I understand correctly the issue is with the reading of the PGN in Winboard. If it is possible to load the PGN for one of you, but not for the other, please make sure that you are using the same settings:
* Use the same Winboard version, e.g., the latest version http://hgm.nubati.net/WinBoard-AA.zip. This is important, because handling of Janggi was changed recently in Winboard.
* Use the large-board version of Fairy-Stockfish, and choose a compatible version to the Winboard version you are using (due to the above mentioned changes). If you use the latest Winboard version, please make sure to download or compile a recent development version of Fairy-Stockfish, e.g., click on the latest build from https://github.com/ianfab/Fairy-Stockfish/actions?query=workflow%3Abuild+branch%3Amaster+is%3Asuccess (you need to be logged in) and download the artifact.
* Setting the exact same Janggi variant perhaps is not required, but if it still does not work, maybe try to use the same.

If after checking that you are using consistent settings, it still does not work, then please post the PGN so that I can check what might be wrong with it.

Yes, https://paypal.me/FairyStockfish and https://www.patreon.com/ianfab are the official links where you can support Fairy-Stockfish development with donations (paypal is for one-time donations, patreon for recurring ones).

**Comment by ianfab** [comment] 2021-02-20 10:07
Closing due to follow-up #261.

**Closed by ianfab** 2021-02-20 10:07 UTC
