### ISSUE TITLE
Question: will you merge from Stockfish

### ISSUE THREAD

**Issue by vochicong** [ianfab/Fairy-Stockfish#17] opened 2019-01-23 08:46 UTC
How often did/will you merge from Stockfish upstream?

I'm going to try the Shogi variant. Thank you!

**Comment by ianfab** [comment] 2019-01-23 16:43
Initially I decided not to do any merges from upstream. However, since the progress in terms of number of supported variants and playing strength was way faster than I had expected, I would really like to regularly merge upstream changes.

I have not done any merges since I started the project half a year ago, but I hope I can start to catch up in the near term. Most likely I will skip some commits or only cherry-pick individual commits, since some parts of the code that relied on properties specific to chess needed to be refactored and will be hard to merge with upstream changes.

If you encounter any issues using Fairy-Stockfish, please let me know. Shogi is not its strong suit so far (since a specialized evaluation is key), but it is quite strong at shogi variants with smaller board sizes.

**Comment by ianfab** [comment] 2019-01-24 11:40
Whether it is a fork or not on github does not really affect merging/pulling on a local git repository, so that is not an issue. Merging is however still not trivial, since for most commits some merge conflicts need to be resolved, so it will take time to catch up with merges.

In terms of playing strength for chess variants, being left behind official stockfish is not really a big problem, since already now this fork is the strongest engine in most of the variants it supports (at least to my knowledge), apart from some variants where there are stronger dedicated engines (mostly shogi engines, and multi-variant Stockfish), usually also based on Stockfish. Still, profiting from upstream improvements and keeping the code base up-to-date would be nice.

I have not tested against the gShogi engine yet (only used the GUI with other engines), but you can find playing strength estimates relative to other engines in the [wiki](https://github.com/ianfab/Fairy-Stockfish/wiki/Playing-strength). As far as I know, gShogi is very weak, so there might be something wrong with the [settings](https://github.com/ianfab/Fairy-Stockfish/wiki/Usage#gshogi) if Fairy-Stockfish does not beat it. I can test tomorrow how it performs against gShogi.

Plugging in an evaluation function like the ones that are used by apery or YaneuraOu would theoretically be possible, but it would not really make sense IMO, since the aforementioned engines are also derived from Stockfish, so using the same evaluation function it would more or less end up to be clone of them and nothing new (at least for shogi). Furthermore, it does not really fit the idea of this project to have dedicated evaluation functions for single variants, since it is supposed to be generic and work well also for similar variants with slightly different rules (e.g., different board sizes). However, I am constantly improving the evaluation function especially for variants with piece drops, i.e., mainly shogi (variants) and crazyhouse, so it should hopefully continue to improve in the future (it already has improved by several hundred Elo in the last few months).

**Comment by vochicong** [comment] 2019-01-25 13:32
Are you using the same **generic** evaluation function for all variants?
If so, when trying to improve the evaluation for one variant, isn't it hard to make sure that it the change is doesn't make bad impact for other variants?

**Comment by ianfab** [comment] 2019-01-25 14:38
The evaluation function is not exactly the same for all variants, but the core idea is to use the features/rules of a variant to decide on which evaluation terms (same with other parts of the code, such as search techniques) to apply or how to adjust them, and not have a separate evaluation for single variants. This way, improvements for one variant usually also improve playing strength in variants that share certain features.

E.g., some evaluation terms are only applied when the rules of a variant include that captured pieces go to the opponent's hand. Changes for such terms I usually only test for crazyhouse, shogi, and maybe minishogi, but playing strength in other shogi variants (euroshogi, judkins shogi, etc.) is also improving on average, although this is of course not guaranteed. E.g., although I never seriously tested most of the shogi variants, Fairy-SF plays them remarkably well (in fact I am currently not aware of any stronger shogi variant engine for minishogi, euroshogi, judkins shogi, etc.).

You are of course right that changes can also sometimes regress playing strength for some untested variants, that is why I usually focus on testing the more popular/important variants and risking regressions only in variants that do not have a high priority to me, but it of course still requires a lot of testing.

A simple example of the idea of basing evaluation terms on the rules of the game is:
https://github.com/ianfab/Fairy-Stockfish/blob/5bbc386cd3a18c7f6a2944d4ffaf0ef1aed6a737/src/evaluate.cpp#L1067 This means that if the rules of a variant includes that captured pieces go to the opponent's hand (shogi, etc.) or that capturing is mandatory (e.g., antichess), the evaluation of the piece mobility is multiplied by a factor of 2 (or 3), since piece mobility seems to be more important in such variants.

**Comment by vochicong** [comment] 2019-01-30 14:50
> This means that if the rules of a variant includes that captured pieces go to the opponent's hand (shogi, etc.) or that capturing is mandatory (e.g., antichess), the evaluation of the piece mobility is multiplied by a factor of 2 (or 3), since piece mobility seems to be more important in such variants.

This idea is new to me and I will think more about it. Thank you.

**Comment by ianfab** [comment] 2019-02-09 19:06
FYI, I started to do upstream merges in the last days and merged around 20 commits so far. The fork is still 170 commits behind official stockfish, so it will perhaps take two or three months to catch up. Although there are quite many merge conflicts, they usually are easy to resolve, so it seems less problematic than I had expected.

**Comment by vochicong** [comment] 2019-02-11 00:32
Good news!
I’m looking at lc0, Stockfish, YaneuraOu and this Fairy one. It looks to me that Fairy has the most “general” architecture.

**Comment by ianfab** [comment] 2019-02-11 16:46
Are you referring to generality with regards to game playing? The other three engines target only a single variant, so they can not really be compared in this regard, although the algorithm behind lc0 can of course be implemented for other games. From a practical point of view, I think this engine is a very good trade-off between general game playing and specialized engines, while it of course does neither achieve true GGP nor a top-notch dedicated single-game engine (although it nevertheless seems to be the strongest engine in around 2/3 of the games it supports).

Engines that support a similar set of chess-like games, i.e., that are comparable to this one in terms of functionality, like Sjaak II, Nebiyu, or FairyMax are around 500 Elo weaker in most variants (see https://github.com/ianfab/Fairy-Stockfish/wiki/Playing-strength), so to my knowledge there currently is no engine with a similar combination of large variety of supported variants and high playing strength, which makes this project so interesting to me.

**Comment by vochicong** [comment] 2019-02-12 01:40
> improvements for one variant usually also improve playing strength in variants that share certain features.

Since reading your comment above and seeing 
https://github.com/ianfab/Fairy-Stockfish/blob/5bbc386cd3a18c7f6a2944d4ffaf0ef1aed6a737/src/evaluate.cpp#L1067 
I started thinking instead of hard coding those rules, what would happen if we we let it play many variants and learn by itself to create and continuously improve  a single neural network that can play many chess variants.

If the neural network has learned a lot about shogi, it may somehow play good chess even if it only knows some basic chess rules.

**Comment by ianfab** [comment] 2019-02-12 13:09
This sounds interesting, but I think it is a rather theoretical idea, since the encoding of the input of the neural network would be quite challenging, not to mention the required computational resources.

E.g., if you want to encode the positions of all pieces, you would either need to have input planes with the maximum board size for each piece type (e.g., 32 piece types on up to 12x10 squares for what we have currently; even if large parts of the piece types and squares are not used for most variants) for an AlphaZero-style input, or you could have piece slots with piece type, file, and rank more similar to Giraffe. The further would be a huge input, while for the latter it has not been demonstrated yet that it can achieve the same playing strength.

Another problem is that the rules of the game also need to be passed as input. In itself this might sound relatively easy (mostly some booleans whether a rule is enabled or not), but how to connect the input features representing the rules with the input planes representing the position is perhaps very tricky, at least if you want to get a decent playing strength. Rules like the board size or promotion zones could quite straightforward be encoded as additional input planes, but if you do it in a similar way for all other rules, the size of the input grows drastically, along with the number of connections to subsequent layers, of course.

Furthermore, the required resources for training would of course be huge, especially considering the large number of variants and input features. As a first step one could of course use supervised training, but even the training data generation and training for this would require much more computation power than just a single machine.

So all in all I think this idea sounds very interesting in principle, but infeasible without massive resources. But maybe DeepMind is already working on one single AlphaZero instance (not separately trained instances) playing Go, Chess, and Shogi, who knows.

**Comment by ianfab** [comment] 2019-03-02 13:44
Update: 100 commits merged, 70 left.

**Comment by ianfab** [comment] 2019-03-30 17:46
Hooray, finally [up to date with official stockfish and CI builds are green](https://github.com/ianfab/Fairy-Stockfish/commits/5d604e1a5d5501e48a7128168f8daa33de985356) :-).

The upstream merges on average seem to consistently improve playing strength for almost all tested variants.

**Closed by ianfab** 2019-03-30 17:46 UTC
Labels: question

**Comment by gbtami** [comment] 2019-03-30 18:18
Time to go for xiangqi :wink: !

**Comment by vochicong** [comment] 2019-03-31 09:43
Excellent!
